# Home task for Module 1
# Create list of 100 random numbers from 0 to 1000
import random  # Import of random module for using of random function

listOfRandom = []  # Define the empty list
for j in range(1000):  # Define of FOR statement with range of iterations from 0 to 999
    listOfRandom.append(random.randint(0, 999))  # Adding of randomly generated by randint function INT values to list
print('List with generated random values:', listOfRandom)  # Printing final list to console
# Sort list from min to max (without using sort())
for run in range(len(listOfRandom) - 1):  # Define of initial FOR statement with range of iterations minus 1 from list
    for i in range(len(listOfRandom) - 1 - run):  # Inner FOR statement with decreasing iterations for each run
        if listOfRandom[i] > listOfRandom[i + 1]:  # Compare two adjacent values from list
            listOfRandom[i], listOfRandom[i + 1] = listOfRandom[i + 1], listOfRandom[i]  # Swap places
print('Sorted from min to max list:', listOfRandom)  # Printing of sorted by bubble sorting list
# Calculate average for even and odd numbers
evenNumbers = []  # Define empty list for even numbers
oddNumbers = []  # Define empty list for odd numbers
for i in range(len(listOfRandom)):  # Define FOR statement with number of iterations equal to list length
    if listOfRandom[i] % 2 == 0:  # Check if number can be divided by 2 without reminder
        evenNumbers.append(listOfRandom[i])  # Adding of even values to separate list
    else:
        oddNumbers.append(listOfRandom[i])  # Else other values added to odd values list
for i in range(len(evenNumbers)):  # Define of FOR statement with range equal to even numbers list length
    total = 0  # Define of variable for calculation of total with 0 value
    total = total + evenNumbers[i]  # Calculation of total sum
evenAverage = total / len(evenNumbers)  # Calculation of average even number
for i in range(len(oddNumbers)):  # Define of FOR statement with range equal to odd numbers list length
    total = 0  # Clearing of total with 0 value
    total = total + oddNumbers[i]  # Calculation of total sum
oddAverage = total / len(oddNumbers)  # Calculation of average odd number
print('Average count of even numbers:', evenAverage)  # Printing of average of even numbers to console
print('Average count of odd numbers:', oddAverage)  # Printing of average of odd numbers to console
